# Generated by Django 5.0.6 on 2024-06-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_medicalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Payment Pending', max_length=20),
        ),
    ]
