# Generated by Django 5.0.6 on 2024-06-27 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
