# Generated by Django 5.0.6 on 2024-06-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_department_image_doctor_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
